### ISSUE TITLE
Unable to load addon script from path: 

### ISSUE THREAD

**Issue by Juan122113** [noidexe/SpriteCutter#3]
Hello. I am very new with this engine and programming. I can't enable the plugin. When I want to do it I get this message:

Unable to load addon script from path: 'res://addons/sprite_cutter/sprite_cutter.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/sprite_cutter/plugin.cfg' to prevent further errors.

And this is what appears in the output:

  res://addons/sprite_cutter/sprite_cutter.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/sprite_cutter/sprite_cutter.gd" with error "Parse error". (User)

**Comment by noidexe** [comment]
What version of Godot are you running?

**Comment by noidexe** [comment]
I'm assuming you're using Godot 4. I've just updated the plugin on the master branch to be compatible. Let me know if it works now

**Comment by Juan122113** [comment]
Yes, I use the latest version of Godot, 4.2. Now I can activate the plugin, I think it works now. The bad thing is that I don't know how to use it.

**Comment by Juan122113** [comment]
I just cropped the image I needed. Now I mark the issue as closed? It's the first time I do this.

**Comment by noidexe** [comment]
Yes you can mark it as closed or I can do it. The protect maintainers can always reopen an issue if it turns out it wasn't really fixed.

Closing as completed. Thanks for reporting! 😊

**Comment by Juan122113** [comment]
Thanks to you!
